modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
[[mods]]
modId="unvotedandshelved"
version="1.18.2-2.0.5-forge"
displayName="Unvoted and Shelved"
logoFile="unvotedandshelved.png"
authors="Dopadream, Orcinus, Ninni, Blackgear, Sydokiddo"
description='''
Introduces the outvoted Mobs from previous mob votes.
'''
[[dependencies.unvotedandshelved]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.unvotedandshelved]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"