package com.cursedcauldron.unvotedandshelved.client.entity;

import com.cursedcauldron.unvotedandshelved.client.entity.animation.Animation;
import com.cursedcauldron.unvotedandshelved.client.entity.animation.AnimationHelper;
import com.cursedcauldron.unvotedandshelved.client.entity.animation.Keyframe;
import com.cursedcauldron.unvotedandshelved.client.entity.animation.Transformation;
import com.cursedcauldron.unvotedandshelved.common.entity.CopperGolemEntity;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;

//<>

@Environment(EnvType.CLIENT)
public class CopperGolemAnimations {
    public static final Animation WALKING = Animation.Builder.create(1.08333F)
            .addBoneAnimation("antenna", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2083F, AnimationHelper.rotation(0.0F, 45.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5833F, AnimationHelper.rotation(0.0F, 45.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.7917F, AnimationHelper.rotation(0.0F, 90.0F, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("antenna", new Transformation(Transformation.Targets.TRANSLATE,
                    new Keyframe(0.0F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.0417F, AnimationHelper.translate(0.0F, -0.3F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.0833F, AnimationHelper.translate(0.0F, -1.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.0938F, AnimationHelper.translate(0.0F, -0.7F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1042F, AnimationHelper.translate(0.0F, -0.5F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1146F, AnimationHelper.translate(0.0F, -0.5F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.125F, AnimationHelper.translate(0.0F, -0.5F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1354F, AnimationHelper.translate(0.0F, -0.7F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1458F, AnimationHelper.translate(0.0F, -1.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1563F, AnimationHelper.translate(0.0F, -0.8F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1667F, AnimationHelper.translate(0.0F, -0.7F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.1771F, AnimationHelper.translate(0.0F, -0.8F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1875F, AnimationHelper.translate(0.0F, -1.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1979F, AnimationHelper.translate(0.0F, -0.8F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.2083F, AnimationHelper.translate(0.0F, -1.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5833F, AnimationHelper.translate(0.0F, -1.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.625F, AnimationHelper.translate(0.0F, -0.7F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.6667F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.6771F, AnimationHelper.translate(0.0F, -0.1F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.6979F, AnimationHelper.translate(0.0F, -0.2F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.7188F, AnimationHelper.translate(0.0F, -0.1F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.7292F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.7917F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0833F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("body", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1042F, AnimationHelper.rotation(0.7F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.2083F, AnimationHelper.rotation(-6.3F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.3542F, AnimationHelper.rotation(-2.3F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.4167F, AnimationHelper.rotation(-0.3F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.4479F, AnimationHelper.rotation(3.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.4792F, AnimationHelper.rotation(6.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5F, AnimationHelper.rotation(7.3F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5833F, AnimationHelper.rotation(1.7F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.6667F, AnimationHelper.rotation(-1.3F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.7917F, AnimationHelper.rotation(-6.3F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.8854F, AnimationHelper.rotation(-4.3F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9896F, AnimationHelper.rotation(5.2F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.0625F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM)
                    ))
            .addBoneAnimation("right_leg", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.0938F, AnimationHelper.rotation(1.9F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.125F, AnimationHelper.rotation(17.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1771F, AnimationHelper.rotation(20.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.2083F, AnimationHelper.rotation(35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.375F, AnimationHelper.rotation(35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.4375F, AnimationHelper.rotation(29.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.5F, AnimationHelper.rotation(10.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5521F, AnimationHelper.rotation(8.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.5833F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.625F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.6667F, AnimationHelper.rotation(-2.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.7083F, AnimationHelper.rotation(-17.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.7604F, AnimationHelper.rotation(-21.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.7917F, AnimationHelper.rotation(-52.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.8542F, AnimationHelper.rotation(-52.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9271F, AnimationHelper.rotation(-39.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.0F, AnimationHelper.rotation(10.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0417F, AnimationHelper.rotation(10.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0625F, AnimationHelper.rotation(7.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.0833F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("right_leg", new Transformation(Transformation.Targets.TRANSLATE,
                    new Keyframe(0.0F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2083F, AnimationHelper.translate(0.0F, 0.0F, 1.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.7917F, AnimationHelper.translate(0.0F, 0.0F, -1.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0833F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("left_leg", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.0938F, AnimationHelper.rotation(-1.9F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.125F, AnimationHelper.rotation(-17.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1771F, AnimationHelper.rotation(-20.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.2083F, AnimationHelper.rotation(-35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.375F, AnimationHelper.rotation(-35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.4375F, AnimationHelper.rotation(-29.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.5F, AnimationHelper.rotation(-10.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5521F, AnimationHelper.rotation(-8.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.5833F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.625F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.6667F, AnimationHelper.rotation(2.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.7083F, AnimationHelper.rotation(17.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.7604F, AnimationHelper.rotation(21.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.7917F, AnimationHelper.rotation(52.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.8542F, AnimationHelper.rotation(52.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9271F, AnimationHelper.rotation(39.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.0F, AnimationHelper.rotation(-10.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0417F, AnimationHelper.rotation(-10.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0625F, AnimationHelper.rotation(-7.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.0833F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("left_leg", new Transformation(Transformation.Targets.TRANSLATE,
                    new Keyframe(0.0F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2083F, AnimationHelper.translate(0.0F, 0.0F, -0.74F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.7917F, AnimationHelper.translate(0.0F, 0.0F, 1F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0833F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("left_arm", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.0625F, AnimationHelper.rotation(10.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.125F, AnimationHelper.rotation(32.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1458F, AnimationHelper.rotation(32.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1667F, AnimationHelper.rotation(33.2F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1875F, AnimationHelper.rotation(37.2F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2083F, AnimationHelper.rotation(42.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.3646F, AnimationHelper.rotation(28.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.5F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5521F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5938F, AnimationHelper.rotation(-4.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.6458F, AnimationHelper.rotation(-20.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.7083F, AnimationHelper.rotation(-47.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.7188F, AnimationHelper.rotation(-46.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.75F, AnimationHelper.rotation(-48.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.7813F, AnimationHelper.rotation(-53.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.7917F, AnimationHelper.rotation(-55.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.8958F, AnimationHelper.rotation(-38.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0833F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("right_arm", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.0625F, AnimationHelper.rotation(-10.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.125F, AnimationHelper.rotation(-32.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1458F, AnimationHelper.rotation(-32.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1667F, AnimationHelper.rotation(-33.2F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1875F, AnimationHelper.rotation(-37.2F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2083F, AnimationHelper.rotation(-42.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.3646F, AnimationHelper.rotation(-28.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.5F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5521F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5938F, AnimationHelper.rotation(4.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.6458F, AnimationHelper.rotation(20.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.7083F, AnimationHelper.rotation(47.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.7188F, AnimationHelper.rotation(46.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.75F, AnimationHelper.rotation(48.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.7813F, AnimationHelper.rotation(53.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.7917F, AnimationHelper.rotation(55.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.8958F, AnimationHelper.rotation(38.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0833F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .looping().build();

    public static final Animation HEAD_SPIN = Animation.Builder.create(0.88542F)
            .addBoneAnimation("head", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.0833F, AnimationHelper.rotation(0.0F, 88.3F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2083F, AnimationHelper.rotation(0.0F, 90.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.2917F, AnimationHelper.rotation(0.0F, 175.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.4167F, AnimationHelper.rotation(0.0F, 180.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.5F, AnimationHelper.rotation(0.0F, 277.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.625F, AnimationHelper.rotation(0.0F, 270.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.75F, AnimationHelper.rotation(0.0F, 359.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.8333F, AnimationHelper.rotation(0.0F, 360.0F, 0.0F), Transformation.Interpolations.CATMULLROM)
                    ))
            .addBoneAnimation("left_arm", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.0833F, AnimationHelper.rotation(-35.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.1667F, AnimationHelper.rotation(-35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2083F, AnimationHelper.rotation(-35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2917F, AnimationHelper.rotation(38.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.375F, AnimationHelper.rotation(37.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.4167F, AnimationHelper.rotation(28.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.5F, AnimationHelper.rotation(-39.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.5833F, AnimationHelper.rotation(-35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.625F, AnimationHelper.rotation(-35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.7292F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.8333F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("right_arm", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.0833F, AnimationHelper.rotation(35.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.1667F, AnimationHelper.rotation(35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2083F, AnimationHelper.rotation(35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2917F, AnimationHelper.rotation(-38.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.375F, AnimationHelper.rotation(-37.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.4167F, AnimationHelper.rotation(-28.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.5F, AnimationHelper.rotation(39.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.5833F, AnimationHelper.rotation(35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.625F, AnimationHelper.rotation(35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.7292F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.8333F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("antenna", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2083F, AnimationHelper.rotation(0.0F, -45.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.625F, AnimationHelper.rotation(0.0F, 360.0F, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("antenna", new Transformation(Transformation.Targets.TRANSLATE,
                    new Keyframe(0.0F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.0313F, AnimationHelper.translate(0.0F, -0.5F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.0625F, AnimationHelper.translate(0.0F, -2.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.0938F, AnimationHelper.translate(0.0F, -1.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.125F, AnimationHelper.translate(0.0F, -2.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.1458F, AnimationHelper.translate(0.0F, -1.5F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.1667F, AnimationHelper.translate(0.0F, -2.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.1875F, AnimationHelper.translate(0.0F, -1.5F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.2083F, AnimationHelper.translate(0.0F, -2.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.625F, AnimationHelper.translate(0.0F, -2.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.6667F, AnimationHelper.translate(0.0F, -1.4F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.6979F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.7396F, AnimationHelper.translate(0.0F, -1.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.7708F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.7917F, AnimationHelper.translate(0.0F, -0.5F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.8125F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.8229F, AnimationHelper.translate(0.0F, -0.2F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.8333F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM)
                    ))
            .build();

    public static final Animation HEAD_SPIN_SLOWER = Animation.Builder.create(1.106775F)
            .addBoneAnimation("head", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.104125F, AnimationHelper.rotation(0.0F, 88.3F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.260375F, AnimationHelper.rotation(0.0F, 90.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.364625F, AnimationHelper.rotation(0.0F, 175.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.520875F, AnimationHelper.rotation(0.0F, 180.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.625F, AnimationHelper.rotation(0.0F, 277.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.78125F, AnimationHelper.rotation(0.0F, 270.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.9375F, AnimationHelper.rotation(0.0F, 359.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.041625F, AnimationHelper.rotation(0.0F, 360.0F, 0.0F), Transformation.Interpolations.CATMULLROM)
            ))

            .addBoneAnimation("left_arm", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.104125F, AnimationHelper.rotation(-35.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.208375F, AnimationHelper.rotation(-35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.260375F, AnimationHelper.rotation(-35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.364625F, AnimationHelper.rotation(38.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.46875F, AnimationHelper.rotation(37.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.520875F, AnimationHelper.rotation(28.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.625F, AnimationHelper.rotation(-39.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.729125F, AnimationHelper.rotation(-35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.78125F, AnimationHelper.rotation(-35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9115F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.041625F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL)
            ))
            .addBoneAnimation("right_arm", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.104125F, AnimationHelper.rotation(35.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.208375F, AnimationHelper.rotation(35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.260375F, AnimationHelper.rotation(35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.364625F, AnimationHelper.rotation(-38.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.46875F, AnimationHelper.rotation(-37.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.520875F, AnimationHelper.rotation(-28.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.625F, AnimationHelper.rotation(39.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.729125F, AnimationHelper.rotation(35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.78125F, AnimationHelper.rotation(35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9115F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.041625F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL)
            ))
            .addBoneAnimation("antenna", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.260375F, AnimationHelper.rotation(0.0F, -45.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.78125F, AnimationHelper.rotation(0.0F, 360.0F, 0.0F), Transformation.Interpolations.LINEAL)
            ))
            .addBoneAnimation("antenna", new Transformation(Transformation.Targets.TRANSLATE,
                    new Keyframe(0.0F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.039125F, AnimationHelper.translate(0.0F, -0.5F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.078125F, AnimationHelper.translate(0.0F, -2.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.11725F, AnimationHelper.translate(0.0F, -1.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.15625F, AnimationHelper.translate(0.0F, -2.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.18225F, AnimationHelper.translate(0.0F, -1.5F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.208375F, AnimationHelper.translate(0.0F, -2.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.234375F, AnimationHelper.translate(0.0F, -1.5F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.260375F, AnimationHelper.translate(0.0F, -2.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.78125F, AnimationHelper.translate(0.0F, -2.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.833375F, AnimationHelper.translate(0.0F, -1.4F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.872375F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.9245F, AnimationHelper.translate(0.0F, -1.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.9635F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.989625F, AnimationHelper.translate(0.0F, -0.5F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.015625F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.98748F, AnimationHelper.translate(0.0F, -0.2F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.041625F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM)
            ))
            .build();

    public static final Animation HEAD_SPIN_SLOWEST = Animation.Builder.create(0.88542F)
            .addBoneAnimation("head", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.12495F,  AnimationHelper.rotation(0.0F, 88.3F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.31245F,  AnimationHelper.rotation(0.0F, 90.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.43755F,  AnimationHelper.rotation(0.0F, 175.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.62505F,  AnimationHelper.rotation(0.0F, 180.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.75F, AnimationHelper.rotation(0.0F, 277.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9375F, AnimationHelper.rotation(0.0F, 270.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.125F, AnimationHelper.rotation(0.0F, 359.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.24995F,  AnimationHelper.rotation(0.0F, 360.0F, 0.0F), Transformation.Interpolations.CATMULLROM)
            ))
            .addBoneAnimation("left_arm", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.12495F,  AnimationHelper.rotation(-35.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.25005F,  AnimationHelper.rotation(-35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.31245F,  AnimationHelper.rotation(-35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.43755F,  AnimationHelper.rotation(38.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.5625F, AnimationHelper.rotation(37.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.62505F,  AnimationHelper.rotation(28.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.75F, AnimationHelper.rotation(-39.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.87495F,  AnimationHelper.rotation(-35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9375F, AnimationHelper.rotation(-35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0938F,  AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.24995F,  AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL)
            ))
            .addBoneAnimation("right_arm", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.12495F, AnimationHelper.rotation(35.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.25005F, AnimationHelper.rotation(35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.31245F, AnimationHelper.rotation(35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.43755F, AnimationHelper.rotation(-38.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.5625F, AnimationHelper.rotation(-37.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.62505F, AnimationHelper.rotation(-28.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.75F, AnimationHelper.rotation(39.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.87495F, AnimationHelper.rotation(35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9375F, AnimationHelper.rotation(35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0938F,  AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.24995F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL)
            ))
            .addBoneAnimation("antenna", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.31245F, AnimationHelper.rotation(0.0F, -45.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9375F, AnimationHelper.rotation(0.0F, 360.0F, 0.0F), Transformation.Interpolations.LINEAL)
            ))
            .addBoneAnimation("antenna", new Transformation(Transformation.Targets.TRANSLATE,
                    new Keyframe(0.0F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.04695F, AnimationHelper.translate(0.0F, -0.5F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.09375F, AnimationHelper.translate(0.0F, -2.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.1407F, AnimationHelper.translate(0.0F, -1.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.1875F,AnimationHelper.translate(0.0F, -2.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.2187F, AnimationHelper.translate(0.0F, -1.5F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.25005F, AnimationHelper.translate(0.0F, -2.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.28125F, AnimationHelper.translate(0.0F, -1.5F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.31245F, AnimationHelper.translate(0.0F, -2.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9375F, AnimationHelper.translate(0.0F, -2.0F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.00005F, AnimationHelper.translate(0.0F, -1.4F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.04685F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.1094F, AnimationHelper.translate(0.0F, -1.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.1562F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.18755F, AnimationHelper.translate(0.0F, -0.5F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.21875F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.23435F, AnimationHelper.translate(0.0F, -0.2F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.24995F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM)
            ))
            .build();


    public static final Animation BUTTON_PRESS = Animation.Builder.create(2.53125F)
            .addBoneAnimation("body", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1667F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.3333F, AnimationHelper.rotation(12.5F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0F, AnimationHelper.rotation(12.5F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.1667F, AnimationHelper.rotation(12.5F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.2396F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.3333F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                   ))
            .addBoneAnimation("body", new Transformation(Transformation.Targets.TRANSLATE,
                    new Keyframe(0.0F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.0F, AnimationHelper.translate(0.0F, 0.02F, 0.005F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.0F, AnimationHelper.translate(0.0F, -0.075F, -0.85F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.0F, AnimationHelper.translate(0.0F, -0.075F, -0.85F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.0F, AnimationHelper.translate(0.0F, -0.075F, -0.85F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.0F, AnimationHelper.translate(0.0F, -0.04F, 0.02F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.0F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                   ))
            .addBoneAnimation("right_leg", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1667F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.3333F, AnimationHelper.rotation(-12.5F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0F, AnimationHelper.rotation(-12.5F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.1667F, AnimationHelper.rotation(-12.5F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.2396F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.3333F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("left_leg", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1667F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.3333F, AnimationHelper.rotation(-12.5F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0F, AnimationHelper.rotation(-12.5F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.1667F, AnimationHelper.rotation(-12.5F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.2396F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.3333F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                   ))
            .addBoneAnimation("left_arm", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1667F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2396F, AnimationHelper.rotation(-56.92445F, -7.9185F, 6.12673F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.3229F, AnimationHelper.rotation(-56.92445F, -7.9185F, 6.12673F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.4896F, AnimationHelper.rotation(-56.92445F, -7.9185F, 6.12673F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5625F, AnimationHelper.rotation(-128.42631F, -7.86484F, 6.19564F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.6667F, AnimationHelper.rotation(-128.42631F, -7.86484F, 6.19564F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.8333F, AnimationHelper.rotation(-128.42631F, -7.86484F, 6.19564F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9167F, AnimationHelper.rotation(-71.10922F, -3.53329F, 3.54002F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.9792F, AnimationHelper.rotation(-56.92445F, -6.9185F, 6.12673F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0938F, AnimationHelper.rotation(-56.92F, -7.92F, 6.13F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.1667F, AnimationHelper.rotation(-56.92445F, -6.9185F, 6.12673F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.3333F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("right_arm", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1667F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2083F, AnimationHelper.rotation(-31.8F, 0, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.25F, AnimationHelper.rotation(-130.24258F, 5.73853F, -4.83711F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.3333F, AnimationHelper.rotation(-127.92445F, 7.9185F, -6.12673F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5F, AnimationHelper.rotation(-127.92445F, 7.9185F, -6.12673F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5625F, AnimationHelper.rotation(-55.0F, 0, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.625F, AnimationHelper.rotation(-55.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.6667F, AnimationHelper.rotation(-55.02635F, -1.98315F, 1.52251F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.8333F, AnimationHelper.rotation(-55.02635F, -1.98315F, 1.52251F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9167F, AnimationHelper.rotation(-135.10922F, 3.53329F, -3.54002F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.0F, AnimationHelper.rotation(-127.92445F, 6.9185F, -6.12673F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.0938F, AnimationHelper.rotation(-127.92F, 6.9185F, -3.54002F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.1667F, AnimationHelper.rotation(-127.92445F, 7.9185F, -6.12673F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.3333F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                   ))
            .addBoneAnimation("head", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1667F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2188F, AnimationHelper.rotation(-7.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2604F, AnimationHelper.rotation(-7.0F, 0, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.3333F, AnimationHelper.rotation(-12.5F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0F, AnimationHelper.rotation(-12.5F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.1667F, AnimationHelper.rotation(-12.5F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.2292F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.3333F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("antenna", new Transformation(Transformation.Targets.TRANSLATE,
                    new Keyframe(0.0F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1667F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1875F, AnimationHelper.translate(0.0F, -0.05F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.2083F, AnimationHelper.translate(0.0F, -2F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2188F, AnimationHelper.translate(0.0F, -1.8F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2396F, AnimationHelper.translate(0.0F, -1.7F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.2604F, AnimationHelper.translate(0.0F, -1.8F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2708F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2917F, AnimationHelper.translate(0.0F, -1.9F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.3125F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.3229F, AnimationHelper.translate(0.0F, -1.9F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.3333F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5313F, AnimationHelper.translate(0.0F, -1.5F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.5625F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5833F, AnimationHelper.translate(0.0F, -0.03F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.6042F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.625F, AnimationHelper.translate(0.0F, -0.1F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.6458F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.6667F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.8333F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.8646F, AnimationHelper.translate(0.0F, -0.5F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.8958F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9271F, AnimationHelper.translate(0.0F, -1.6F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.9583F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9688F, AnimationHelper.translate(0.0F, -1.9F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.0F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.1667F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.25F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.3333F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .build();

    public static final Animation BUTTON_PRESS_UP = Animation.Builder.create(2.70833F)
            .addBoneAnimation("body", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.1667F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.3333F, AnimationHelper.rotation(-20, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0F, AnimationHelper.rotation(-20, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.125F, AnimationHelper.rotation(-20, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.375F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("body", new Transformation(Transformation.Targets.TRANSLATE,
                    new Keyframe(0.0F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1667F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2083F, AnimationHelper.translate(0.0F, 0.005F, 0.35F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.25F, AnimationHelper.translate(0.0F, -0.045F, 0.69F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2917F, AnimationHelper.translate(0.0F, -0.115F, 1.03F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.3333F, AnimationHelper.translate(0.0F, -0.241F, 1.375F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0F, AnimationHelper.translate(0.0F, -0.241F, 1.375F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.125F, AnimationHelper.translate(0.0F, -0.241F, 1.375F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.375F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("right_leg", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.1667F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.3333F, AnimationHelper.rotation(20, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0F, AnimationHelper.rotation(20, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.125F, AnimationHelper.rotation(20, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.375F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("left_leg", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.1667F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.3333F, AnimationHelper.rotation(20, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0F, AnimationHelper.rotation(20, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.125F, AnimationHelper.rotation(20, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.375F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("left_arm", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1667F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2396F, AnimationHelper.rotation(-56.92445F, -7.9185F, 6.12673F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.3229F, AnimationHelper.rotation(-56.92445F, -7.9185F, 6.12673F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.4896F, AnimationHelper.rotation(-56.92445F, -7.9185F, 6.12673F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5625F, AnimationHelper.rotation(-128.42631F, -7.86484F, 6.19564F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.6667F, AnimationHelper.rotation(-128.42631F, -7.86484F, 6.19564F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.8333F, AnimationHelper.rotation(-128.42631F, -7.86484F, 6.19564F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9167F, AnimationHelper.rotation(-71.10922F, -3.53329F, 3.54002F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.9792F, AnimationHelper.rotation(-56.92445F, -6.9185F, 6.12673F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0938F, AnimationHelper.rotation(-56.92F, -7.92F, 6.13F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.1667F, AnimationHelper.rotation(-56.92445F, -6.9185F, 6.12673F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.3333F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("right_arm", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1667F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2083F, AnimationHelper.rotation(-31.8F, 0, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.25F, AnimationHelper.rotation(-130.24258F, 5.73853F, -4.83711F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.3333F, AnimationHelper.rotation(-127.92445F, 7.9185F, -6.12673F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5F, AnimationHelper.rotation(-127.92445F, 7.9185F, -6.12673F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5625F, AnimationHelper.rotation(-55.0F, 0, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.625F, AnimationHelper.rotation(-55.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.6667F, AnimationHelper.rotation(-55.02635F, -1.98315F, 1.52251F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.8333F, AnimationHelper.rotation(-55.02635F, -1.98315F, 1.52251F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9167F, AnimationHelper.rotation(-135.10922F, 3.53329F, -3.54002F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.0F, AnimationHelper.rotation(-127.92445F, 6.9185F, -6.12673F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.0938F, AnimationHelper.rotation(-127.92F, 6.9185F, -3.54002F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.1667F, AnimationHelper.rotation(-127.92445F, 7.9185F, -6.12673F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.3333F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("head", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.1667F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.25F, AnimationHelper.rotation(-39.75F, 0, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.3333F, AnimationHelper.rotation(-39.75F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.1667F, AnimationHelper.rotation(-39.75F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.25F, AnimationHelper.rotation(-39.75F, 0, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.375F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("antenna", new Transformation(Transformation.Targets.TRANSLATE,
                    new Keyframe(0.0F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1667F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1875F, AnimationHelper.translate(0.0F, -0.05F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.2083F, AnimationHelper.translate(0.0F, -2F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2188F, AnimationHelper.translate(0.0F, -1.8F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2396F, AnimationHelper.translate(0.0F, -1.7F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.2604F, AnimationHelper.translate(0.0F, -1.8F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2708F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2917F, AnimationHelper.translate(0.0F, -1.9F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.3125F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.3229F, AnimationHelper.translate(0.0F, -1.9F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.3333F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5313F, AnimationHelper.translate(0.0F, -1.5F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.5625F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5833F, AnimationHelper.translate(0.0F, -0.03F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.6042F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.625F, AnimationHelper.translate(0.0F, -0.1F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.6458F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.6667F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.8333F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.8646F, AnimationHelper.translate(0.0F, -0.5F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.8958F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9271F, AnimationHelper.translate(0.0F, -1.6F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.9583F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9688F, AnimationHelper.translate(0.0F, -1.9F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.0F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.1667F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.25F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.3333F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .build();

    public static final Animation BUTTON_PRESS_DOWN = Animation.Builder.create(1.79167F)
            .addBoneAnimation("body", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.1667F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.3333F, AnimationHelper.rotation(32.5F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0F, AnimationHelper.rotation(32.5F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.1667F, AnimationHelper.rotation(32.5F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.4167F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("body", new Transformation(Transformation.Targets.TRANSLATE,
                    new Keyframe(0.0F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1667F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2083F, AnimationHelper.translate(0, -0.045F, -0.575F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.25F, AnimationHelper.translate(0, -0.145F, -1.11F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2917F, AnimationHelper.translate(0, -0.34F, -1.645F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.3333F, AnimationHelper.translate(0, -0.616F, -2.15F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0F, AnimationHelper.translate(0, -0.616F, -2.15F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.1667F, AnimationHelper.translate(0, -0.616F, -2.15F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.4167F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("right_leg", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.1667F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.3333F, AnimationHelper.rotation(-32.5F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0F, AnimationHelper.rotation(-32.5F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.1667F, AnimationHelper.rotation(-32.5F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.4167F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("left_leg", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.1667F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.3333F, AnimationHelper.rotation(-32.5F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0F, AnimationHelper.rotation(-32.5F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.1667F, AnimationHelper.rotation(-32.5F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.4167F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("left_arm", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1667F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2396F, AnimationHelper.rotation(-56.92445F, -7.9185F, 6.12673F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.3229F, AnimationHelper.rotation(-56.92445F, -7.9185F, 6.12673F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.4896F, AnimationHelper.rotation(-56.92445F, -7.9185F, 6.12673F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5625F, AnimationHelper.rotation(-128.42631F, -7.86484F, 6.19564F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.6667F, AnimationHelper.rotation(-128.42631F, -7.86484F, 6.19564F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.8333F, AnimationHelper.rotation(-128.42631F, -7.86484F, 6.19564F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9167F, AnimationHelper.rotation(-71.10922F, -3.53329F, 3.54002F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.9792F, AnimationHelper.rotation(-56.92445F, -6.9185F, 6.12673F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0938F, AnimationHelper.rotation(-56.92F, -7.92F, 6.13F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.1667F, AnimationHelper.rotation(-56.92445F, -6.9185F, 6.12673F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.3333F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("right_arm", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1667F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2083F, AnimationHelper.rotation(-31.8F, 0, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.25F, AnimationHelper.rotation(-130.24258F, 5.73853F, -4.83711F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.3333F, AnimationHelper.rotation(-127.92445F, 7.9185F, -6.12673F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5F, AnimationHelper.rotation(-127.92445F, 7.9185F, -6.12673F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5625F, AnimationHelper.rotation(-55.0F, 0, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.625F, AnimationHelper.rotation(-55.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.6667F, AnimationHelper.rotation(-55.02635F, -1.98315F, 1.52251F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.8333F, AnimationHelper.rotation(-55.02635F, -1.98315F, 1.52251F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9167F, AnimationHelper.rotation(-135.10922F, 3.53329F, -3.54002F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.0F, AnimationHelper.rotation(-127.92445F, 6.9185F, -6.12673F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.0938F, AnimationHelper.rotation(-127.92F, 6.9185F, -3.54002F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.1667F, AnimationHelper.rotation(-127.92445F, 7.9185F, -6.12673F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.3333F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("head", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.1667F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2083F, AnimationHelper.rotation(19.25F, 0, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.3333F, AnimationHelper.rotation(20, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.0F, AnimationHelper.rotation(20, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.1667F, AnimationHelper.rotation(20, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.2917F, AnimationHelper.rotation(-1.75F, 0, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.4167F, AnimationHelper.rotation(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .addBoneAnimation("antenna", new Transformation(Transformation.Targets.TRANSLATE,
                    new Keyframe(0.0F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1667F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.1875F, AnimationHelper.translate(0.0F, -0.05F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.2083F, AnimationHelper.translate(0.0F, -2F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2188F, AnimationHelper.translate(0.0F, -1.8F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2396F, AnimationHelper.translate(0.0F, -1.7F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.2604F, AnimationHelper.translate(0.0F, -1.8F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2708F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.2917F, AnimationHelper.translate(0.0F, -1.9F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.3125F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.3229F, AnimationHelper.translate(0.0F, -1.9F, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.3333F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5313F, AnimationHelper.translate(0.0F, -1.5F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.5625F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.5833F, AnimationHelper.translate(0.0F, -0.03F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.6042F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.625F, AnimationHelper.translate(0.0F, -0.1F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.6458F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.6667F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.8333F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.8646F, AnimationHelper.translate(0.0F, -0.5F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.8958F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9271F, AnimationHelper.translate(0.0F, -1.6F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(0.9583F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(0.9688F, AnimationHelper.translate(0.0F, -1.9F, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.0F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.1667F, AnimationHelper.translate(0.0F, -2, 0.0F), Transformation.Interpolations.LINEAL),
                    new Keyframe(1.25F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.CATMULLROM),
                    new Keyframe(1.3333F, AnimationHelper.translate(0.0F, 0, 0.0F), Transformation.Interpolations.LINEAL)
                    ))
            .build();
    
    public static Animation walkingAnimation(CopperGolemEntity.Stage stage) {
        float modifier = getSpeedModifier(stage);

        return Animation.Builder.create(1.08333F * modifier)
                .addBoneAnimation("antenna", new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.2083F * modifier, AnimationHelper.rotation(0.0F, 45.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.5833F * modifier, AnimationHelper.rotation(0.0F, 45.0F, 0.0F), Transformation.Interpolations.LINEAL), new Keyframe(0.7917F * modifier, AnimationHelper.rotation(0.0F, 90.0F, 0.0F), Transformation.Interpolations.LINEAL)
                ))
                .addBoneAnimation("antenna", new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0.0F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.0417F * modifier, AnimationHelper.translate(0.0F, -0.3F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.0833F * modifier, AnimationHelper.translate(0.0F, -1.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.0938F * modifier, AnimationHelper.translate(0.0F, -0.7F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.1042F * modifier, AnimationHelper.translate(0.0F, -0.5F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.1146F * modifier, AnimationHelper.translate(0.0F, -0.5F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.125F * modifier, AnimationHelper.translate(0.0F, -0.5F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.1354F * modifier, AnimationHelper.translate(0.0F, -0.7F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.1458F * modifier, AnimationHelper.translate(0.0F, -1.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.1563F * modifier, AnimationHelper.translate(0.0F, -0.8F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.1667F * modifier, AnimationHelper.translate(0.0F, -0.7F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.1771F * modifier, AnimationHelper.translate(0.0F, -0.8F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.1875F * modifier, AnimationHelper.translate(0.0F, -1.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.1979F * modifier, AnimationHelper.translate(0.0F, -0.8F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.2083F * modifier, AnimationHelper.translate(0.0F, -1.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.5833F * modifier, AnimationHelper.translate(0.0F, -1.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.625F * modifier, AnimationHelper.translate(0.0F, -0.7F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.6667F * modifier, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.6771F * modifier, AnimationHelper.translate(0.0F, -0.1F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.6979F * modifier, AnimationHelper.translate(0.0F, -0.2F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.7188F * modifier, AnimationHelper.translate(0.0F, -0.1F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.7292F * modifier, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.7917F * modifier, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(1.0833F * modifier, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL)
                ))
                .addBoneAnimation("body", new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.1042F * modifier, AnimationHelper.rotation(0.7F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.2083F * modifier, AnimationHelper.rotation(-6.3F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.3542F * modifier, AnimationHelper.rotation(-2.3F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.4167F * modifier, AnimationHelper.rotation(-0.3F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.4479F * modifier, AnimationHelper.rotation(3.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.4792F * modifier, AnimationHelper.rotation(6.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.5F * modifier, AnimationHelper.rotation(7.3F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.5833F * modifier, AnimationHelper.rotation(1.7F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.6667F * modifier, AnimationHelper.rotation(-1.3F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.7917F * modifier, AnimationHelper.rotation(-6.3F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.8854F * modifier, AnimationHelper.rotation(-4.3F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.9896F * modifier, AnimationHelper.rotation(5.2F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(1.0625F * modifier, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM)
                ))
                .addBoneAnimation("right_leg", new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.0938F * modifier, AnimationHelper.rotation(1.9F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.125F * modifier, AnimationHelper.rotation(17.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.1771F * modifier, AnimationHelper.rotation(20.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.2083F * modifier, AnimationHelper.rotation(35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.375F * modifier, AnimationHelper.rotation(35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.4375F * modifier, AnimationHelper.rotation(29.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.5F * modifier, AnimationHelper.rotation(10.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.5521F * modifier, AnimationHelper.rotation(8.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.5833F * modifier, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.625F * modifier, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.6667F * modifier, AnimationHelper.rotation(-2.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.7083F * modifier, AnimationHelper.rotation(-17.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.7604F * modifier, AnimationHelper.rotation(-21.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.7917F * modifier, AnimationHelper.rotation(-52.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.8542F * modifier, AnimationHelper.rotation(-52.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.9271F * modifier, AnimationHelper.rotation(-39.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(modifier, AnimationHelper.rotation(10.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(1.0417F * modifier, AnimationHelper.rotation(10.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(1.0625F * modifier, AnimationHelper.rotation(7.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(1.0833F * modifier, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL)
                ))
                .addBoneAnimation("right_leg", new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0.0F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.2083F * modifier, AnimationHelper.translate(0.0F, 0.0F, 1.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.5F * modifier, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.7917F * modifier, AnimationHelper.translate(0.0F, 0.0F, -1.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(1.0833F * modifier, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL)
                ))
                .addBoneAnimation("left_leg", new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.0938F * modifier, AnimationHelper.rotation(-1.9F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.125F * modifier, AnimationHelper.rotation(-17.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.1771F * modifier, AnimationHelper.rotation(-20.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.2083F * modifier, AnimationHelper.rotation(-35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.375F * modifier, AnimationHelper.rotation(-35.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.4375F * modifier, AnimationHelper.rotation(-29.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.5F * modifier, AnimationHelper.rotation(-10.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.5521F * modifier, AnimationHelper.rotation(-8.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.5833F * modifier, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.625F * modifier, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.6667F * modifier, AnimationHelper.rotation(2.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.7083F * modifier, AnimationHelper.rotation(17.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.7604F * modifier, AnimationHelper.rotation(21.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.7917F * modifier, AnimationHelper.rotation(52.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.8542F * modifier, AnimationHelper.rotation(52.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.9271F * modifier, AnimationHelper.rotation(39.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(modifier, AnimationHelper.rotation(-10.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(1.0417F * modifier, AnimationHelper.rotation(-10.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(1.0625F * modifier, AnimationHelper.rotation(-7.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(1.0833F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL)
                ))
                .addBoneAnimation("left_leg", new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0.0F, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.2083F * modifier, AnimationHelper.translate(0.0F, 0.0F, -0.74F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.5F * modifier, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.7917F * modifier, AnimationHelper.translate(0.0F, 0.0F, 1F), Transformation.Interpolations.LINEAL),
                        new Keyframe(modifier, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(1.0833F * modifier, AnimationHelper.translate(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL)
                ))
                .addBoneAnimation("left_arm", new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.0625F * modifier, AnimationHelper.rotation(10.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.125F * modifier, AnimationHelper.rotation(32.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.1458F * modifier, AnimationHelper.rotation(32.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.1667F * modifier, AnimationHelper.rotation(33.2F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.1875F * modifier, AnimationHelper.rotation(37.2F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.2083F * modifier, AnimationHelper.rotation(42.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.3646F * modifier, AnimationHelper.rotation(28.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.5F * modifier, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.5521F * modifier, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.5938F * modifier, AnimationHelper.rotation(-4.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.6458F * modifier, AnimationHelper.rotation(-20.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.7083F * modifier, AnimationHelper.rotation(-47.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.7188F * modifier, AnimationHelper.rotation(-46.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.75F * modifier, AnimationHelper.rotation(-48.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.7813F * modifier, AnimationHelper.rotation(-53.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.7917F * modifier, AnimationHelper.rotation(-55.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.8958F * modifier, AnimationHelper.rotation(-38.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(modifier, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(1.0833F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL)
                ))
                .addBoneAnimation("right_arm", new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0.0F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.0625F * modifier, AnimationHelper.rotation(-10.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.125F * modifier, AnimationHelper.rotation(-32.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.1458F * modifier, AnimationHelper.rotation(-32.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.1667F * modifier, AnimationHelper.rotation(-33.2F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.1875F * modifier, AnimationHelper.rotation(-37.2F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.2083F * modifier, AnimationHelper.rotation(-42.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.3646F * modifier, AnimationHelper.rotation(-28.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.5F * modifier, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.5521F * modifier, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.5938F * modifier, AnimationHelper.rotation(4.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.6458F * modifier, AnimationHelper.rotation(20.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.7083F * modifier, AnimationHelper.rotation(47.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.7188F * modifier, AnimationHelper.rotation(46.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.75F * modifier, AnimationHelper.rotation(48.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(0.7813F * modifier, AnimationHelper.rotation(53.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.7917F * modifier, AnimationHelper.rotation(55.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(0.8958F * modifier, AnimationHelper.rotation(38.0F, 0.0F, 0.0F), Transformation.Interpolations.CATMULLROM),
                        new Keyframe(modifier, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL),
                        new Keyframe(1.0833F, AnimationHelper.rotation(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAL)
                ))
                .looping().build();
    }

    private static float getSpeedModifier(CopperGolemEntity.Stage stage) {
        return switch (stage) {
            case UNAFFECTED, OXIDIZED -> 1.0F;
            case EXPOSED -> 1.55F;
            case WEATHERED -> 1.85F;
        };
    }
}